### ISSUE TITLE
inReadTop View

### ISSUE THREAD

**Issue by akshit019** [teads/TeadsSDK-ReactNative#1]
Hi, thank you for giving out this example. Can you please explain how the object is passed in viewGroup while creating mTeadsAd and is it possible to use inReadTop way of displaying Teads AdView. Thank you

**Comment by HugoGresse** [comment]
Hi @akshit019 thanks for your patience. I'm closing this before updating the repo with the new Teads SDK v4. Let me know if you have still some issue.
